CREATE DATABASE goods;
USE goods;
CREATE TABLE gtab(name VARCHAR(40), price INT);
INSERT INTO gtab VALUES ('TV',600);
INSERT INTO gtab VALUES('X-BOX',450);
ALTER table gtab
	ADD COLUMN id  INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY(id);
SELECT * FROM gtab;
DROP DATABASE goods;