CREATE DATABASE testch5;
USE testch5;


CREATE TABLE post (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
P_ID INT NOT NULL,
post VARCHAR(50) NOT NULL);

CREATE TABLE person (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL,
surname VARCHAR(40) NOT NULL,
FOREIGN KEY(ID) REFERENCES POST(P_ID));
